### ISSUE TITLE
gulp serve sometimes can't load CSS

### ISSUE THREAD

**Issue by bluetch** [bluetch/solar#1]
I miss something, so that when I cmd gulp serve, sometimes it can not load CSS style. But for gulp build its work, could anyone help me? thank you

**Comment by SaraSpink** [comment]
I am having the opposite experience; the build does not have the CSS but the serve seems to show your styling. I am not sure how to proceed however. Good luck!

**Comment by viswanathamsantosh** [comment]
+1 to what @SaraSpink said. Added 'styles' task to gulp build. let me know how it goes. https://github.com/bluetch/solar/pull/2

**Comment by lachieh** [comment]
This should be closed in #2, correct?

**Comment by bluetch** [comment]
Yes, thanks your remind @lachieh !
